add saveAs function
DimensionDev/kit pull request #1
Opened 2020-11-26 06:19 UTC by zhouhanseng

2020-11-26 06:20 UTC, zhouhanseng commented on package.json
> +    "web-ext-types": "^3.2.1"
declare `browser` type

2020-11-26 06:21 UTC, septs commented on package.json
> +    "web-ext-types": "^3.2.1"
peer

2020-11-26 06:28 UTC, septs requested changes

2020-11-26 06:28 UTC, septs commented on src/saveAs.ts
> +})
```suggestion
const createDownloadElement = (href: string, fileName = "") => {
  const element = document.createElement('a')
  element.href = url
  element.download = fileName
  return element
}
```

this is wrong usage

```
> wrap = _.once((foo) => foo)
> wrap(1)
< 1
> wrap(2)
< 1
> wrap()
< 1
```

2020-11-26 06:28 UTC, septs commented on src/saveAs.ts
> +export function saveAsFile(file: ArrayBuffer, mineType: string, suggestingFileName: string, isAndroid: boolean) {
```suggestion
export function saveAsFile(source: BufferSource, mimeType: string, fileName = "", isAndroid = true) {
```

2020-11-26 08:01 UTC, zhouhanseng commented on package.json
> +    "web-ext-types": "^3.2.1"
when use peer dep, throw error:

![image](https://user-images.githubusercontent.com/63733714/100323379-9d2c6e00-3000-11eb-9b0b-a40072fb4a9b.png)

2020-12-28 08:44 UTC, septs approved these changes

2020-12-28 08:44 UTC, merged